[package]
name = "shell_vm"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"

[dependencies]
bstr = "1.9"
caseless = "0.2"
anyhow = "1.0"
filedescriptor = "0.8"
filenamegen = { path = "../filenamegen" }
lazy_static = "1.3"

[dev-dependencies]
pretty_assertions = "0.6"
